FROM alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/alinux3:latest AS base
RUN dnf install -y curl tar gzip && dnf clean all
COPY aigon-agent-qwen-society /usr/local/bin/
COPY standalone.yaml /opt/aigon-hack/config.yaml
EXPOSE 7000
ENV QWEN_API_KEY="sk-2243bf91ff064b29bdb18d9419cc2c04"
ENV QWEN_ENDPOINT="https://ws-h3ayxryayp3b7ad5.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"
ENV QWEN_MODEL="qwen3.7-max"
CMD ["aigon-agent-qwen-society", "--mode", "standalone", "--config", "/opt/aigon-hack/config.yaml"]
